---
- name: Copy the file
  hosts: all
  tasks:
    - name: Coply file copy
      copy:
        src: /root/Project-Capstone-Ansible/copy.yml
        dest: /root
        owner: root
        mode: '700'
