--- 
- name: Apply security policies
  hosts: all
  become: yes
  tasks:
    - name: Disable to ssh as root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Ensure firewalld is enabled and running perfectly
      service: 
        name: firewalld
        state: started
        enabled: yes

    - name: Disable SELinux
      selinux: 
        state: disabled

  handlers: 
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
