# playbook.yml
- name: Prepare all nodes
  hosts: all
  become: yes
  roles:
    - k8s-common

- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  roles:
    - k8s-master

- name: Join Worker Nodes to the Cluster
  hosts: worker
  become: yes
  roles:
    - k8s-worker