---
- name: Secure MySQL user creation using Vault and limited privileges
  hosts: db1
  become: yes

  vars:
    db_admin_user: "luckyfriday"
    db_allowed_host: "%"
    db_name: "Team1"  # Replace with your database

  vars_files:
    - secrets.yml

  tasks:

    - name: Construct SQL command for user creation
      set_fact:
        create_user_sql: >
          CREATE USER IF NOT EXISTS '{{ db_admin_user }}'@'{{ db_allowed_host }}' IDENTIFIED BY '{{ db_admin_password }}';

    - name: Construct SQL command for granting limited privileges
      set_fact:
        grant_privileges_sql: >
          GRANT SELECT, INSERT, UPDATE ON {{ db_name }}.* TO '{{ db_admin_user }}'@'{{ db_allowed_host }}';

    - name: Construct SQL command for revoking all privileges
      set_fact:
        revoke_privileges_sql: >
          REVOKE ALL PRIVILEGES, GRANT OPTION FROM '{{ db_admin_user }}'@'{{ db_allowed_host }}';

    - name: Execute user creation command
      shell: >
        mysql -u root --password='{{ db_root_password }}' -e "{{ create_user_sql }}"
      no_log: true  # hides password from logs

    - name: Revoke all existing privileges before applying limited ones
      shell: >
        mysql -u root --password='{{ db_root_password }}' -e "{{ revoke_privileges_sql }}"
      no_log: true

    - name: Grant limited privileges
      shell: >
        mysql -u root --password='{{ db_root_password }}' -e "{{ grant_privileges_sql }}"
      no_log: true

    - name: Flush privileges
      shell: >
        mysql -u root --password='{{ db_root_password }}' -e "FLUSH PRIVILEGES;"
      no_log: true
