---
- name: Install and configure MariaDB, create user and grant privileges
  hosts: db1
  become: true

  vars:
    packages_to_install:
      - epel-release
      - mariadb
      - mariadb-server

    db_root_password: "password"
    db_user: "root"
    db_user_password: "password"
    db_name: "*"

  tasks:
    - name: Install required packages
      dnf:
        name: "{{ packages_to_install }}"
        state: present

    - name: Ensure MariaDB service is started and enabled
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Create MariaDB user
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_user_password }}';"
        # args:
        # warn: false

    - name: Grant privileges to the user
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'localhost'; FLUSH PRIVILEGES;"
        #args:
        #warn: false

