---
- name: Configure HAProxy Load Balancer
  hosts: haproxy1
  become: yes
  vars:
   frontend_port: 80
   backend_port: 80
   load_balance_algorithm: roundrobin
   backend_servers:
     - { name: "web1", host: "prdx-webserver101.ziyotek1.local" }
     - { name: "web2", host: "prdx-webserver102.ziyotek1.local" }
     - { name: "web3", host: "prdx-webserver103.ziyotek1.local" }
 
  tasks:
    - name: Install HAProxy
      yum:
        name: haproxy
        state: present
 
    - name: Copy HAProxy config from template
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
 
    - name: Start and enable HAProxy
      service:
        name: haproxy
        state: started
        enabled: true

    - name: Open port 80/tcp in Firewalld
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true
