---
- name: Install BIND packages
  ansible.builtin.yum:
    name:
      - bind
      - bind-utils
    state: present

- name: Deploy named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'
  notify: Restart named

- name: Deploy forward zone
  ansible.builtin.template:
    src: db.forward.j2
    dest: /var/named/db.forward
    owner: named
    group: named
    mode: '0640'
  notify: Restart named

- name: Deploy reverse zone
  ansible.builtin.template:
    src: db.reverse.j2
    dest: /var/named/db.reverse
    owner: named
    group: named
    mode: '0640'
  notify: Restart named

- name: Enable and start named service
  systemd:
    name: named
    enabled: yes
    state: started
